// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    IklanKecil: typeof import('./src/components/IklanKecil.svelte')['default']
    IklanKotak: typeof import('./src/components/IklanKotak.svelte')['default']
    IklanMelayang: typeof import('./src/components/IklanMelayang.svelte')['default']
    Island: typeof import('iles')['Island']
    JumlahPeserta: typeof import('./src/components/JumlahPeserta.svelte')['default']
    KelasHariIni: typeof import('./src/components/KelasHariIni.svelte')['default']
    Komentar: typeof import('./src/components/Komentar.svelte')['default']
    Meta: typeof import('./src/components/Meta.svelte')['default']
    'Meta.svelte': typeof import('./src/components/Meta.svelte.vue')['default']
    Peserta: typeof import('./src/components/Peserta.svelte')['default']
    Social: typeof import('./src/components/Social.svelte')['default']
    WindiGradient: typeof import('./src/components/WindiGradient.svelte')['default']
  }
}

export { }
