baseURL = "https://belajarpemrograman.my.id/"
languageCode = "en-us"
title = "<BP/>"
theme = "hugo-ink"
paginate = 10

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# oogleAnalyticss = "G-0EVHX122V8"
disqusShortname = "belajarpemrogramanzen"

[outputs]
  section = ["html", "rss", "json"]
 
[params]
	subtitle = "Yuk belajar pemrograman"

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/tentang-penulis"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Cari"
url = "/cari"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mzaini30/belajar-pemrograman"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[permalinks]
  posts = "/:title/"